name: Publish Kata release artifacts for amd64
on:
  workflow_call:
    inputs:
      target-arch:
        required: true
        type: string

jobs:
  build-kata-static-tarball-amd64:
    uses: ./.github/workflows/build-kata-static-tarball-amd64.yaml
    with:
      stage: release
